# Generated by Django 2.1.7 on 2019-06-12 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidades', models.IntegerField()),
                ('fechacarga', models.DateField(default=datetime.date.today)),
                ('total_gasto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listaprecios',
            fields=[
                ('id', models.SlugField(max_length=256, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=256, null=True)),
                ('precio_producto', models.IntegerField(null=True)),
                ('categoria_producto', models.CharField(max_length=20, null=True)),
                ('cantidad_producto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombre_cliente', models.CharField(max_length=256, null=True)),
                ('comentario', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productosordenados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Listaprecios')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Tiposdegastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=42)),
                ('unidadmedicion', models.CharField(choices=[('kg', 'Kg'), ('un', 'Unidad')], max_length=30)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('insumos', 'Insumos'), ('mp', 'Materia prima')], max_length=40)),
                ('stockeable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Tiposdegastos'),
        ),
    ]
