# Generated by Django 2.1.7 on 2019-07-02 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=40, unique=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidades', models.IntegerField()),
                ('fechacarga', models.DateField(default=datetime.date.today)),
                ('total_gasto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listaprecios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=256)),
                ('precio_producto', models.IntegerField()),
                ('categoria_producto', models.CharField(choices=[('rolls', 'Rolls'), ('calientes', 'Calientes'), ('barcos', 'Barcos'), ('puentes', 'Puentes'), ('bd', 'Barcos descartables'), ('laja', 'Lajas'), ('varios', 'Varios')], max_length=20)),
                ('sub_categoria_producto', models.CharField(choices=[('hotroll', 'Hot Rolls'), ('otros', 'Otros'), ('simples', 'Simples'), ('clasicos', 'Clasicos'), ('especiales', 'Especiales'), ('premiums', 'Premiums'), ('salsa', 'Salsas'), ('bocados', 'Bocados')], max_length=20)),
                ('cantidad_producto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('comentario', models.CharField(blank=True, max_length=256, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productosordenados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Listaprecios')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Tiposdegastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=42)),
                ('unidadmedicion', models.CharField(choices=[('kg', 'Kg'), ('un', 'Unidad')], max_length=30)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('insumos', 'Insumos'), ('mp', 'Materia prima')], max_length=40)),
                ('stockeable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsuki_app.Tiposdegastos'),
        ),
    ]
