# Generated by Django 2.1.7 on 2019-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecios',
            name='sub_categoria_producto',
            field=models.CharField(choices=[('hotroll', 'Hot Rolls'), ('otros', 'Otros'), ('simples', 'Simples'), ('clasicos', 'Clasicos'), ('especiales', 'Especiales'), ('premiums', 'Premiums'), ('salsa', 'Salsas'), ('bocados', 'Bocados'), ('surtido', 'Surtido'), ('salmon', 'Salmon'), ('veggie', 'Veggie'), ('premium', 'Premium')], max_length=20),
        ),
    ]
