# Generated by Django 2.1.7 on 2019-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0002_auto_20190703_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdegastos',
            name='sub_categoria',
            field=models.CharField(choices=[('verduleria', 'Verduleria'), ('descartable', 'Descartables'), ('cong/frios', 'Congelados/Frios'), ('secos/conservas', 'Secos/Conservas'), ('otros', 'Otros')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdegastos',
            name='categoria',
            field=models.CharField(choices=[('servicios', 'Servicios'), ('personal', 'Personal'), ('productos', 'Productos'), ('impuestos', 'Impuestos')], max_length=40, null=True),
        ),
    ]
