# Generated by Django 2.1.7 on 2019-07-18 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0003_auto_20190714_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
