# Generated by Django 2.2.4 on 2019-08-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0006_productosordenados_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosordenados',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tsuki_app.Listaprecios'),
        ),
    ]
