# Generated by Django 2.2.4 on 2019-10-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0008_auto_20191007_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='entregado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='impreso',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
