# Generated by Django 2.2.4 on 2019-11-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0009_auto_20191029_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='impreso',
        ),
    ]
