# Generated by Django 2.2.4 on 2020-02-02 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0010_auto_20191106_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosordenados',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tsuki_app.Listaprecios'),
        ),
    ]
