# Generated by Django 2.2.4 on 2020-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0012_auto_20200202_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='direnvio',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
