# Generated by Django 2.2.4 on 2021-03-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuki_app', '0014_auto_20200708_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecios',
            name='sub_categoria_producto',
            field=models.CharField(choices=[('hotroll', 'Hot Rolls'), ('otros', 'Otros'), ('clasicos', 'Clasicos'), ('especiales', 'Especiales'), ('premiums', 'Premiums'), ('veggies', 'Veggies'), ('veggie', 'Veggie'), ('salsa', 'Salsas'), ('bocados', 'Bocados'), ('surtido', 'Surtido'), ('salmon', 'Salmon'), ('postres', 'Postres')], max_length=20),
        ),
    ]
